runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /.*
  script: blog-short-for-weblog.app

libraries:
- name: jinja2
  version: latest